manual_selection = ['Country name',
'Country code',
 'Year',
 'Region',
 'Income group',
 'Adult populaiton',
 'Account (% age 15+)',
 'Financial institution account (% age 15+)',
 'Owns a credit card (% age 15+)',
 'Owns a debit card (% age 15+)',
 'Used a debit card (% age 15+)',
 'Owns a debit or credit card (% age 15+)',
 'Used a debit or credit card (% age 15+)',
 'Used a mobile phone or the internet to check account balance (% age 15+)',
 'Used a mobile phone or the internet to check account balance (% with a financial institution account, age 15+)',
 'Use a mobile phone or the internet to make payments, buy things, or to send or receive money using a financial institution account (% age 15+)',
 'Use a mobile phone or the internet to make payments, buy things, or to send or receive money using a financial institution account (% with a financial institution account, age 15+)',
 'Made a deposit (% with a financial institution account, age 15+)',
 'Has an inactive account (% age 15+)',
 'Has an inactive account (% with an account, age 15+)',
 'Deposited money into a financial institution account 2 or more times a month (% age 15+)',
 'Deposited money into a financial institution account 2 or more times a month (% who had deposited money, age 15+)',
 'Made a withdrawal (% with a financial institution account, age 15+)',
 'Withdrew money from a financial institution account 2 or more times a month (% age 15+)',
 'Withdrew money from a financial institution account 2 or more times a month (% who had withdrawn money, age 15+)',
 'Store money using a financial institution (% age 15+)',
 'Store money using a financial institution (% with a financial institution account, age 15+)',
 'Store money using a financial institution or a mobile money account (% age 15+)',
 'Store money using a financial institution or a mobile money account (% with an account,  age 15+)',
 'Has access to the internet (% age 15+)',
 'Own a mobile phone (% age 15+)',
 'Saved any money (% age 15+)',
 'Saved at a financial institution (% age 15+)',
 'Saved at a financial institution or using a mobile money account (% age 15+)',
 'Saved for old age (% age 15+)',
 'Borrowed any money (% age 15+)',
 'Borrowed any money from a formal financial institution or using a mobile money account (% age 15+)',
 'Borrowed for health or medical purposes (% age 15+)',
 'Borrowed from a formal financial institution (% age 15+)',
 'Borrowed from family or friends (% age 15+)',
 'Made or received a digital payment (% age 15+)',
 'Made a digital payment (% age 15+)',
 'Received digital payments (% age 15+)',
 'Used a mobile phone or the internet to buy something online (% age 15+)',
 'Used a mobile phone or the internet to pay bills (% age 15+)',
 'Used a mobile phone or the internet to send money (% age 15+)',
 'Made a digital in-store merchant payment: using a mobile phone (% age 15+)',
 'Made a utility payment (% age 15+)',
 'Made a utility payment: using a financial institution account (% age 15+)',
 'Made a utility payment: using a financial institution account (% who paid utility bills, age 15+)',
 'Made a utility payment: using a mobile phone (% age 15+)',
 'Made a utility payment: using a mobile phone (% who paid utility bills, age 15+)',
 'Made a utility payment: using an account (% age 15+)',
 'Made a utility payment: using an account (% who paid utility bills, age 15+)',
 'Made a utility payment: using cash only (% age 15+)',
 'Made a utility payment: using cash only (% who paid utility bills, age 15+)',
 'Received wages (% age 15+)',
 'Received wages: through a mobile phone (% age 15+)',
 'Received wages: through a mobile phone (% of wage recipients, age 15+)',
 'Received wages: to a card (% age 15+)',
 'Received wages: to a card (% of wage recipients, age 15+)',
 'Received wages: into a financial institution account (% age 15+)',
 'Received wages: into a financial institution account (% of wage recipients, age 15+)',
 'Received wages: into an account (% age 15+)',
 'Received wages: into an account (% of wage recipients, age 15+)',
 'Received wages: in cash only (% age 15+)',
 'Received wages: in cash only (% of wage recipients, age 15+)',
 'Received public sector wages (% age 15+)',
 'Received public sector wages: through a mobile phone (% age 15+)',
 'Received public sector wages: through a mobile phone (% of public sector wage recipients, age 15+)',
 'Received public sector wages: to a card (% age 15+)',
 'Received public sector wages: to a card (% of public sector wage recipients, age 15+)',
 'Received public sector wages: into a financial institution account (% age 15+)',
 'Received public sector wages: into a financial institution account (% of public sector wage recipients, age 15+)',
 'Received public sector wages: into an account (% age 15+)',
 'Received public sector wages: into an account (% of public sector wage recipients, age 15+)',
 'Received public sector wages: in cash only (% age 15+)',
 'Received public sector wages: in cash only (% of public sector wage recipients, age 15+)',
 'Received private sector wages (% age 15+)',
 'Received private sector wages: through a mobile phone (% age 15+)',
 'Received private sector wages: through a mobile phone (% of private sector wage recipients, age 15+)',
 'Received private sector wages: to a card (% age 15+)',
 'Received private sector wages: to a card (% of private sector wage recipients, age 15+)',
 'Received private sector wages: into a financial institution account (% age 15+)',
 'Received private sector wages: into a financial institution account (% of private sector wage recipients, age 15+)',
 'Received private sector wages: into an account (% age 15+)',
 'Received private sector wages: into an account (% of private sector wage recipients, age 15+)',
 'Received private sector wages: in cash only (% age 15+)',
 'Received private sector wages: in cash only (% of private sector wage recipients, age 15+)',
 'Received government transfer (% age 15+)',
 'Received a public sector pension (% age 15+)',
 'Received government transfer or pension (% age 15+)',
 'Received government payments (% age 15+)',
 'Received government payments: through a mobile phone (% age 15+)',
 'Received government payments: through a mobile phone (% of government payment recipients, age 15+)',
 'Received government payments: to a card (% age 15+)',
 'Received government payments: to a card (% of government payment recipients, age 15+)',
 'Received government payments: into a financial institution account (% age 15+)',
 'Received government payments: into a financial institution account (% of government payment recipients, age 15+)',
 'Received government payments: into an account (% age 15+)',
 'Received government payments: into an account (% of government payment recipients, age 15+)',
 'Received government payments: in cash only (% age 15+)',
 'Received government payments: in cash only (% of government payment recipients, age 15+)',
 'Worried about not being able to pay for medical costs in case of a serious illness or accident: very worried (% age 15+)',
 'Worried about not being able to pay school fees or fees for education: very worried (% age 15+)',
 'Worried about not having enough money for old age: very worried (% age 15+)',
 'Worried about not having enough money for monthly expenses or bills: very worried (% age 15+)',
 'Main source of emergency funds in 30 days: family or friends (% age 15+)',
 'Main source of emergency funds in 30 days: loan from a bank, employer, or private lender (% age 15+)',
 'Main source of emergency funds in 7 days: family or friends (% age 15+)',
 'Main source of emergency funds in 7 days: loan from a bank, employer, or private lender (% age 15+)',
 'Account, female (% age 15+)',
 'Account, male (% age 15+)',
 'Financial institution account, female (% age 15+)',
 'Financial institution account, male (% age 15+)',
 'Owns a credit card, female (% age 15+)',
 'Owns a credit card, male (% age 15+)',
 'Owns a debit card, female (% age 15+)',
 'Owns a debit card, male (% age 15+)',
 'Saved any money, female (% age 15+)',
 'Saved any money, male (% age 15+)',
 'Saved at a financial institution, female (% age 15+)',
 'Saved at a financial institution, male (% age 15+)',
 'Saved at a financial institution or using a mobile money account, female (% age 15+)',
 'Saved at a financial institution or using a mobile money account, male (% age 15+)',
 'Borrowed any money, female (% age 15+)',
 'Borrowed any money, male (% age 15+)',
 'Borrowed any money from a formal financial institution or using a mobile money account, female (% age 15+)',
 'Borrowed any money from a formal financial institution or using a mobile money account, male (% age 15+)',
 'Borrowed for health or medical purposes, female (% age 15+)',
 'Borrowed for health or medical purposes, male (% age 15+)',
 'Made or received a digital payment, female (% age 15+)',
 'Made or received a digital payment, male (% age 15+)',
 'Made a digital payment, female (% age 15+)',
 'Made a digital payment, male (% age 15+)',
 'Received digital payments, female (% age 15+)',
 'Received digital payments, male (% age 15+)',
 'Made a digital in-store merchant payment: using a mobile phone, female (% age 15+)',
 'Made a digital in-store merchant payment: using a mobile phone, male (% age 15+)',
 'Used a mobile phone or the internet to buy something online, female (% age 15+)',
 'Used a mobile phone or the internet to buy something online, male (% age 15+)',
 'Used a mobile phone or the internet to pay bills, female (% age 15+)',
 'Used a mobile phone or the internet to pay bills, male (% age 15+)',
 'Used a mobile phone or the internet to send money, female (% age 15+)',
 'Used a mobile phone or the internet to send money, male (% age 15+)',
 'Made a utility payment, female (% age 15+)',
 'Made a utility payment, male (% age 15+)',
 'Received wages, female (% age 15+)',
 'Received wages, male (% age 15+)',
 'Received public sector wages, female (% age 15+)',
 'Received public sector wages, male (% age 15+)',
 'Received private sector wages, female (% age 15+)',
 'Received private sector wages, male (% age 15+)',
 'Received government transfer, female (% age 15+)',
 'Received government transfer, male (% age 15+)',
 'Received government transfer or pension, female (% age 15+)',
 'Received government transfer or pension, male (% age 15+)',
 'Received government payments, female (% age 15+)',
 'Received government payments, male (% age 15+)']
